title: "Валера Трусевич"
description: "Personal essays and technical writing."
url: "https://truetnoth.com"
baseurl: ""
lang: "ru"
timezone: "Europe/Moscow"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  writing:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - _writing/.obsidian
